name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  build_runner: ^2.4.14
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  go_router: ^14.7.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3
  talker: ^4.6.7
  talker_dio_logger: ^4.6.7
  talker_flutter: ^4.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/