// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBivVBjuwyhnVmyIXpeOfUn9FeWiCg-Ixk',
    appId: '1:927798109191:web:9ad47b9363dfcbf63a36a2',
    messagingSenderId: '927798109191',
    projectId: 'newsbrief-eaba9',
    authDomain: 'newsbrief-eaba9.firebaseapp.com',
    storageBucket: 'newsbrief-eaba9.firebasestorage.app',
    measurementId: 'G-7RC1FB620L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh2Lh3QFSm5sYclXjxkBsw6sFvf0DNimk',
    appId: '1:927798109191:android:aa1be4dd137143b83a36a2',
    messagingSenderId: '927798109191',
    projectId: 'newsbrief-eaba9',
    storageBucket: 'newsbrief-eaba9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBivVBjuwyhnVmyIXpeOfUn9FeWiCg-Ixk',
    appId: '1:927798109191:web:831f3b4e4ef8c2013a36a2',
    messagingSenderId: '927798109191',
    projectId: 'newsbrief-eaba9',
    authDomain: 'newsbrief-eaba9.firebaseapp.com',
    storageBucket: 'newsbrief-eaba9.firebasestorage.app',
    measurementId: 'G-R6XDPPJJTM',
  );
}
